### ISSUE TITLE
Failed Build for haproxy-docker-alpine:2.9.2

### ISSUE THREAD

**Issue by cmason3** [haproxytech/haproxy-docker-alpine#11]
You are probably already aware, but the GitHub Action to publish HAProxy 2.9.2 with QUIC support to Docker Hub failed yesterday. It looks to be something to do with a Go dependency within the build process.

**Comment by dkorunic** [comment]
Thanks, fixed in https://github.com/haproxytech/haproxy-docker-alpine/commit/84de9cc0e543a828f6bf4edcc9df7a2cd1dc72de and the build is incoming.
