### ISSUE TITLE
HAProxy 2.3 does not start anymore

### ISSUE THREAD

**Issue by MG2R** [haproxytech/haproxy-docker-alpine#2]
I'm running the 2.3 image tag, the last time I pulled in, it was using digest `sha256:550d16425a8810429e18342219fded8d7ce0aeef29f8798dd921bb66ced10222`, which starts just fine. I tried pulling in today and got digest `sha256:faa9d1b9f616fdff190ac21f5516055ece2c34476dab8ae0e3da41a118080334`. However, now haproxy won't start anymore, displaying the following in the log:

> [NOTICE] 135/170514 (1) : New program 'api' (7) forked
> [NOTICE] 135/170514 (1) : New worker #1 (8) forked
> time="2021-05-16T17:05:14Z" level=fatal msg="open /etc/haproxy/dataplaneapi.hcl: no such file or directory"
> [NOTICE] 135/170514 (1) : haproxy version is 2.3.10-4764f0e
> [ALERT] 135/170514 (1) : Current program 'api' (7) exited with code 1 (Exit)
> [ALERT] 135/170514 (1) : exit-on-failure: killing every processes with SIGTERM
> [ALERT] 135/170514 (1) : Current worker #1 (8) exited with code 143 (Terminated)
> [WARNING] 135/170514 (1) : All workers exited. Exiting... (1)

I inspected both images and it seems neither of them have a file called `dataplaneapi.hcl`. However, the old image had a file called `/dataplaneapi.yaml`. Is it possible a recent change broke this or am I missing somethingi configuration wise?

I assumed that a tag would remain backwards compatible. Is that assumption wrong? 

Thanks!

**Comment by MG2R** [comment]
It appears my original analysis is wrong. `/dataplaneapi.yaml` is not in the original container image, but seems to be generated when that original container starts, somehow.

**Comment by dkorunic** [comment]
Hi, this is related to a new [dataplaneapi](https://github.com/haproxytech/dataplaneapi) and should be created in dataplaneapi [issues tracker](https://github.com/haproxytech/dataplaneapi/issues), please.
In terms of how this has happened to enter 2.3 image, we regularly rebuild 2.3 images with latest versions of HAProxy 2.3 and Dataplane.

**Comment by dkorunic** [comment]
Fixed by 3469cd21387d7b7ee8b56defee6f3e0fc1a8a547. Closing.
