### ISSUE TITLE
How to setup SSL certificate for HTTS using Docker HAProxy >= 2.4

### ISSUE THREAD

**Issue by ithieund** [haproxytech/haproxy-docker-alpine#4]
Hello HAProxy team,
I have just followed the guide at https://www.haproxy.com/blog/how-to-run-haproxy-with-docker/ (haproxy v2.4) and it worked like a charm for HTTP (port 80), but I can not find anywhere how to setup SSL with that version.

Can you please help me to overcome this problem?
Thank you so much!

**Comment by bedis** [comment]
Hi
I think you can simply put your certs in your 'haproxy' directory, and reference them like this:
```
frontend myfrontend
  bind :80
  bind :443 ssl crt /usr/local/etc/haproxy/certs/mycert.pem
```

**Comment by dkorunic** [comment]
@ithieund As @bedis has written above, pretty much any directory works but we in general prefer `/usr/local/etc/haproxy/certs` or `/usr/local/etc/ssl`. We would recommend mounting a separate volume for certificates and that's about it.

**Comment by ithieund** [comment]
Thank you very much @bedis and @dkorunic !
