### ISSUE TITLE
Enable QUIC support on 2.6 version

### ISSUE THREAD

**Issue by JuniorJPDJ** [haproxytech/haproxy-docker-alpine#6]
Hello!

I was waiting for QUIC/H3 support in haproxy and when its released there are no official containers with QUIC support available :<

**Comment by dkorunic** [comment]
@JuniorJPDJ Trouble with building HAProxy with QUIC/H3 is that it relies on 3rd party OpenSSL forks such as https://github.com/quictls/openssl. Building default HAProxy image against such fork (non-distro and possibly not maintained and/or not having security patches backported from upstream) would mean that we are pushing such image to all our users (we have several project derived from this base image) which possibly wouldn't appreciate us doing so.
We will most likely do another (separate) image just with QUIC/H3 support.

**Comment by JuniorJPDJ** [comment]
Another image is good for me ;D

Anyway: AFAIK quictls is being updated and rebased after all openssl releases.

**Comment by dkorunic** [comment]
More on the whole QUIC situation by Willy himself: https://github.com/haproxy/haproxy/issues/680#issuecomment-1433118828

**Comment by dkorunic** [comment]
QUIC specific Alpine build can be found here: [https://github.com/haproxytech/haproxy-docker-alpine-quic](https://github.com/haproxytech/haproxy-docker-alpine-quic)
