### ISSUE TITLE
Forking the repository causes flood of failed scheduled workflows

### ISSUE THREAD

**Issue by mclueppers** [haproxytech/haproxy-docker-alpine#8]
The [Version update check and release](https://github.com/haproxytech/haproxy-docker-alpine/blob/main/.github/workflows/update.yml) workflow comes with a schedule attached. Unfortunately, when I synced my fork to latest `main` I started getting emails that the task is failing, since I don't have the secret set for my repo. Is it possible to add conditional statement for the steps and only execute if the secret is there?

**Comment by dkorunic** [comment]
No problem, but it is possible to also [disable any workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) in your repo as well.

**Comment by mclueppers** [comment]
Thanks for the guidance 👍🏻
