### ISSUE TITLE
Wrong link in README.md

### ISSUE THREAD

**Issue by sidious38** [haproxytech/haproxy-docker-alpine#9]
The link to "examples" in the section "How to use this image" is broken.

The name of the default branch has been changed.

OLD Link: https://github.com/haproxy/haproxy/tree/main/examples
NEW Link: https://github.com/haproxy/haproxy/tree/master/examples

**Comment by dkorunic** [comment]
Resolved in https://github.com/haproxytech/haproxy-docker-alpine/commit/c4e3938ba265b1a45e2f4743598b248fdd46527d. Thank you!
